dist: xenial
language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - flake8 --show-source .
  - pytest

notifications:
  email: false
